### ISSUE TITLE
Error at startup starting with version 12-28 and split3/split6 addons

### ISSUE THREAD

**Issue by CollinChaffin** [tablacus/TablacusExplorer#179]
Suddenly as of te181228, the following error appears at startup.  It appears the recent changes in common.js, script.js, index.js and having the split3 and split6 addons installed and enabled (no active splits) is the cause.  However, nothing in my config changed from 12-27 I simply updated the TE and addon code.  Simply disabling those two addons (leaving them installed) and restarting TE results in no more error, but obviously this is critical since it appears those 2 addons are not working at all.

Error:
```
TypeError: Unable to get property 'SetButtons' of undefined or null reference
  at Function code (Function code: 120:2)
  at LoadAddon (file://D:/Tablacus/script/common.js:3567:6)
  at ArrangeAddons (file://D:/Tablacus/script/index.js:2121:7)
  at Global code (file://D:/Tablacus/script/index.js:3617:1) 
addons\split3\script.js

TypeError: Unable to get property 'SetButtons' of undefined or null reference
  at Function code (Function code: 120:2)
  at LoadAddon (file://D:/Tablacus/script/common.js:3567:6)
  at ArrangeAddons (file://D:/Tablacus/script/index.js:2121:7)
  at Global code (file://D:/Tablacus/script/index.js:3617:1) 
addons\split6\script.js
```

**Comment by tablacus** [comment]
Thanks for your report.
Please try  to update "Split 1.06", "Split3 1.03" and "Split6 1.02".

Regards,

**Comment by CollinChaffin** [comment]
Sorry thought I closed this, the issue was quickly resolved with the new version(s).  Thanks!
